---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: apiserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: apiserver
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: apiserver
  name: apiserver
spec:
  replicas: 3
  selector:
    matchLabels:
      run: apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: apiserver
    spec:
      containers:
      - image: biqmind/todo-api
        name: apiserver
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: image-data
      volumes:
      - name: image-data
        persistentVolumeClaim:
          claimName: image-data
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: todo-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: todo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: todo-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: todo-app
    spec:
      containers:
      - image: biqmind/todo-app
        name: todo-app
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hw-ingress
spec:
  rules:
  - host: todo.127.0.0.1.nip.io
    http:
      paths:
      - backend:
          serviceName: todo-app
          servicePort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: example-nfs
  resources:
    requests:
      storage: 1Gi
